import { Document } from 'mongoose';

interface IUser extends Document {
  email?: string;
  username: string;
  password: string;
  salt?: string;
}

interface UserDef {
  email?: string;
  username?: string;
  password?: string;
  salt?: string;
}

interface UserI {
  email: string;
  username: string;
  password: string;
  profiles: Array<ProfileI>;
}

interface ProfileI {
  provider: string; // github, facebook, google, etc.
  id: string; // A unique identifier for the user, as generated by the service provider.
  displayName: string; // The name of this user, suitable for display.
  emails: Array<EmailI>; //The "type" of email address (home, work, etc.).
  photos: Array<PhotoI>; // URL to photos
  };
  
  interface EmailI {
      value: string, 
      type: string
  }
  
  interface PhotoI {
       value: string 
  }

export {ProfileI, IUser, UserDef}

export default UserI